### ISSUE TITLE
Draw forecast using d3

### ISSUE THREAD

**Issue by dns-mcdaid** [RajahBimmy/SentimentForecast#2]
Make it so when plotted points are selected, it will pull up the most popular post from a given period of time (~week, ~month? think this through).

**Comment by dns-mcdaid** [comment]
Also find a way to do predictive future forecasting by keeping a running log of all the data we have available and determining the general deviation.

**Comment by hannavas** [comment]
Ello. Won't the the x-axis indicate the point in time at which the sentiments were collected? So would selecting the plotted point pull up the most popular post on that specific day? Or do you mean that we'll plot points at week-long/month-long increments? (・_・ヾ

**Comment by dns-mcdaid** [comment]
We're parsing three files here (this is a bit confusing, I know, but works best for keeping our data clean.) One is just recording sentiment change over a period of time, the others contain the specific data for both tumblr and twitter posts. By breaking it up, the stock report itself will only from one json file, while the specific data will only be accessed if called.
